remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"
locale: "en-US"
title: "Computer Science Notes"
subtitle: "Bar-Ilan University"
name: "Hodaya Kash"
description: "Lecture notes for Computer Science degree courses"
url: "https://hodayakashh.github.io"
baseurl: "/BIU-ComputerScience"

# Display settings
search: true
search_full_content: true
